[phases.setup]
nixPkgs = ["python310", "sqlite"]

[phases.install]
cmds = ["python -m venv /app/.venv", ". /app/.venv/bin/activate && pip install --upgrade pip && pip install -r requirements.txt"]

[phases.build]
cmds = ["apt-get update && apt-get install -y libsqlite3-dev"]

[start]
cmd = ". /app/.venv/bin/activate && uvicorn app.main:app --host 0.0.0.0 --port ${PORT}"